version: 0.1

dev:
  deploy:
    parameters:
      stack_name: 'cies-cr-infrastructure-dev'
      s3_bucket: cies-cr-infrastructure-dev
      resolve_s3: false
      s3_prefix: 'cies-cr-dev'
      region: 'us-east-1'
      Stage: 'dev'
      confirm_changeset: true
      capabilities: CAPABILITY_NAMED_IAM
      disable_rollback: false
      parameter_overrides: stage=dev

prprd:
  deploy:
    parameters:
      stack_name: 'cies-cr-infrastructure-prprd'
      s3_bucket: cies-cr-infrastructure-prprd
      resolve_s3: false
      s3_prefix: 'cies-cr-prprd'
      region: 'us-east-1'
      Stage: 'prprd'
      confirm_changeset: true
      capabilities: CAPABILITY_NAMED_IAM
      disable_rollback: false
      parameter_overrides: stage=prprd

prod:
  deploy:
    parameters:
      stack_name: 'cies-cr-infrastructure-prod'
      s3_bucket: cies-cr-infrastructure-prod
      resolve_s3: false
      s3_prefix: 'cies-cr-prod'
      region: 'us-east-1'
      Stage: 'prod'
      confirm_changeset: true
      capabilities: CAPABILITY_NAMED_IAM
      disable_rollback: false
      parameter_overrides: stage=prod
